language: generic

services:
  - docker

after_success: 
  - docker build -t minhchien01/online-shop-app .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push minhchien01/online-shop-app

deploy: 
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: my-online_shop
  env: My-onlineshop-env
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  brucket_name: "my-onlineshop-bucket"
  brucket_path: "docker"
  on:
    branch: multi_containers
    